version: '3.2'
services:
  postgres:
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "DB_USER=vini"
      - "DB_PASSWORD=vini"
      - "DB_DATABASE=vinidb"
      - "POSTGRES_PASSWORD=password"
    build: './db'
    networks:
      infranet:
        aliases:
          - 'postgres'

networks:
  infranet:
