version: '3.2'
services:
  postgres:
    # restart: 'always'
    container_name: pgdb
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - "DB_USER=my_user"
      - "DB_PASSWORD=my_password"
      - "DB_DATABASE=my_database"
      - "POSTGRES_PASSWORD=password"
    build: './db'
    networks:
      infranet:
        aliases:
          - 'postgres'

networks:
  infranet:
